
#########################################################################
# Site Settings & Variables
#########################################################################

title: hypepat
email: pat@hypepat.com
author: Pat Gaffney
baseurl: ""
url: "http://hypepat.com"
twitter_username: patrickrgaffney
github_username:  patrickrgaffney
timezone: America/Chicago


#########################################################################
# Build Settings & Variables
#########################################################################

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: minima

gems:
  - jekyll-feed

# Exclude these directories/files from site generation.
exclude: [
  TODO,
  README.md,
  Gemfile,
  Gemfile.lock
]
