
#########################################################################
# Site Settings & Variables
#########################################################################

title: hypepat
email: pat@hypepat.com
author: Pat Gaffney
baseurl: ""
url: "http://hypepat.com"
twitterurl: https://twitter.com/patrickrgaffney
githuburl:  https://github.com/patrickrgaffney
emailurl: mailto:pat@hypepat.com
timezone: America/Chicago
permalink: /:year/:title
destination: hypepat.com


#########################################################################
# Tags Collection
#########################################################################

collections:
    topics:
        output: true
        permalink: /topics/:path

#########################################################################
# Build Settings & Variables
#########################################################################

markdown: redcarpet
highlighter: pygments

redcarpet:
    extensions: [
        "smart", 
        "fenced_code_blocks", 
        "strikethrough",
        "footnotes"
    ]

gems:
  - jekyll-feed

# Exclude these directories/files from site generation.
exclude: [
  TODO,
  README.md,
  Gemfile,
  Gemfile.lock
]
