
#########################################################################
# Site Settings & Variables
#########################################################################

title: hypepat
email: pat@hypepat.com
author: Pat Gaffney
baseurl: ""
url: "http://hypepat.com"
twitter_username: patrickrgaffney
github_username:  patrickrgaffney
timezone: America/Chicago
permalink: /:year/:title


#########################################################################
# Build Settings & Variables
#########################################################################

markdown: redcarpet
highlighter: pygments

redcarpet:
    extensions: [
        "smart", 
        "fenced_code_blocks", 
        "strikethrough",
        "footnotes"
    ]

gems:
  - jekyll-feed

# Exclude these directories/files from site generation.
exclude: [
  TODO,
  README.md,
  Gemfile,
  Gemfile.lock
]
